import prettier from 'eslint-config-prettier';
import { fileURLToPath } from 'node:url';
import { includeIgnoreFile } from '@eslint/compat';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

const gitignorePath = fileURLToPath(new URL('./.gitignore', import.meta.url));

export default defineConfig(
    includeIgnoreFile(gitignorePath),
    js.configs.recommended,
    ...ts.configs.recommended,
    ...svelte.configs.recommended,
    prettier,
    ...svelte.configs.prettier,
    {
        languageOptions: {
            globals: { ...globals.browser, ...globals.node },
        },
        ignores: ['**/*.test.ts'],
        rules: {
            'array-callback-return': ['error', { checkForEach: false }],
            'block-scoped-var': 'error',
            camelcase: 'error',
            complexity: ['error', { max: 20 }],
            'consistent-return': 'error',
            'default-case-last': 'error',
            'default-param-last': 'error',
            'dot-notation': 'error',
            eqeqeq: 'error',
            'guard-for-in': 'error',
            'max-classes-per-file': ['error', 1],
            'max-depth': 'error',
            'max-lines-per-function': ['error', { max: 100, skipBlankLines: true, skipComments: true }],
            'max-params': ['error', 4],
            'new-cap': 'error',
            'no-alert': 'error',
            'no-array-constructor': 'error',
            'no-console': 'error',
            'no-constructor-return': 'error',
            'no-duplicate-imports': ['error', { includeExports: true }],
            'no-else-return': 'error',
            'no-eval': 'error',
            'no-implicit-coercion': 'error',
            'no-inner-declarations': ['error', 'both'],
            'no-lonely-if': 'error',
            'no-loop-func': 'error',
            'no-multi-assign': 'error',
            'no-negated-condition': 'error',
            'no-nested-ternary': 'error',
            'no-new-wrappers': 'error',
            'no-object-constructor': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': 'error',
            'no-promise-executor-return': 'error',
            'no-proto': 'error',
            'no-return-assign': 'error',
            'no-self-compare': 'error',
            'no-shadow': 'error',
            'no-template-curly-in-string': 'error',
            'no-throw-literal': 'error',
            'no-undefined': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unneeded-ternary': 'error',
            'no-unreachable-loop': 'error',
            'no-unused-expressions': 'error',
            'no-useless-concat': 'error',
            'no-useless-return': 'error',
            'no-var': 'error',
            'prefer-arrow-callback': 'error',
            'prefer-object-has-own': 'error',
            'prefer-object-spread': 'error',
            'prefer-promise-reject-errors': 'error',
            'prefer-regex-literals': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'error',
            radix: 'error',
            'require-atomic-updates': 'error',
            'require-await': 'error',
            'require-unicode-regexp': 'error',
            // typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
            // see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
            'no-undef': 'off',
            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                },
            ],
        },
    },
    {
        files: ['**/*.test.ts'],
        rules: {
            'array-callback-return': ['error', { checkForEach: false }],
            'block-scoped-var': 'error',
            camelcase: 'warn',
            'default-case-last': 'error',
            'default-param-last': 'error',
            'dot-notation': 'error',
            eqeqeq: 'error',
            'guard-for-in': 'error',
            'new-cap': 'error',
            'no-alert': 'error',
            'no-array-constructor': 'error',
            'no-console': 'error',
            'no-constructor-return': 'error',
            'no-else-return': 'warn',
            'no-eval': 'error',
            'no-implicit-coercion': 'error',
            'no-inner-declarations': ['error', 'both'],
            'no-lonely-if': 'warn',
            'no-loop-func': 'error',
            'no-multi-assign': 'error',
            'no-negated-condition': 'error',
            'no-new-wrappers': 'error',
            'no-object-constructor': 'error',
            'no-octal-escape': 'error',
            'no-promise-executor-return': 'error',
            'no-proto': 'error',
            'no-return-assign': 'error',
            'no-self-compare': 'error',
            'no-shadow': 'error',
            'no-template-curly-in-string': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unneeded-ternary': 'error',
            'no-unreachable-loop': 'error',
            'no-useless-concat': 'error',
            'no-useless-return': 'error',
            'no-var': 'error',
            'prefer-object-spread': 'error',
            'prefer-promise-reject-errors': 'error',
            'prefer-regex-literals': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            // typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
            // see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
            'no-undef': 'off',
            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                },
            ],
        },
    },
    {
        files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
        languageOptions: {
            parserOptions: {
                projectService: true,
                extraFileExtensions: ['.svelte'],
                parser: ts.parser,
                svelteConfig,
            },
        },
    },
);
